# Generated by Django 5.0.4 on 2024-04-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_accounts_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='SubjectName',
            field=models.CharField(default='Default Subject Name', max_length=100),
        ),
    ]
